# Generated by Django 3.2.14 on 2022-07-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220722_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='file',
            field=models.FileField(blank=True, upload_to='detail/file'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(upload_to='detail/image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, upload_to='product/file'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='prodcut/image'),
        ),
    ]
