# Generated by Django 2.1.15 on 2022-07-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220725_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='URLに表示される名前'),
        ),
    ]
